config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :articles
  resources :notions
  resources :comments
  post "comment/new/:id" => "comment#create", as: :create_comment

  get 'pages/home'

  get 'pages/choice'

  get 'pages/ensavoirplus'

  get 'home/choice'

  root :to => "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id                 :integer          not null, primary key
#  titre              :string
#  content            :text
#  date               :date
#  photo_file_name    :string
#  photo_content_type :string
#  photo_file_size    :integer
#  photo_updated_at   :datetime
#  audio_file_name    :string
#  audio_content_type :string
#  audio_file_size    :integer
#  audio_updated_at   :datetime
#  video_file_name    :string
#  video_content_type :string
#  video_file_size    :integer
#  video_updated_at   :datetime
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Article < ApplicationRecord
  has_and_belongs_to_many :notions

  validates :titre,  presence: true
  validates :content,  presence: true
  validates :year,  presence: true
  has_attached_file :photo
  has_attached_file :video
  has_attached_file :audio

  validates_attachment_content_type :photo, content_type:/^image\/.+/i
  validates_attachment_content_type :audio, content_type: /^audio\/.+/i
  validates_attachment_content_type :video, content_type: /^video\/.+/i



end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  name       :string
#  birthday   :date
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :notion
end

app/models/notion.rb
# == Schema Information
#
# Table name: notions
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Notion < ApplicationRecord
  has_and_belongs_to_many :articles
  has_many :comments
  has_attached_file :photo

  validates_attachment_content_type :photo, content_type: /^image\/.+/i



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    @notions = Notion.all
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    puts '------------------'
    puts article_params[:notion_ids].to_json
    puts '------------------'
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit( :titre, :year, :content, :photo, :audio, :video, :notion_ids => [])
    end
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

  def create
    @notion = Notion.find(params[:id])
    @comment = Comment.new(comment_params)
    @comment[:notion_id] = @notion.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @notion, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @notion }
      else
        format.html { render :new }
        format.json { render json: @notion.errors, status: :unprocessable_entity }
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:name, :birthday, :content)
  end
end

app/controllers/notions_controller.rb
class NotionsController < ApplicationController
  before_action :set_notion, only: [:show, :edit, :update, :destroy]

  # GET /notions
  # GET /notions.json
  def index
    @notions = Notion.all
  end

  # GET /notions/1
  # GET /notions/1.json
  def show
  @notion = Notion.find(params[:id])
  respond_to do |format|
    format.html  # show.html.erb
    format.json  { render :json => @post }
  end
  @articles = Article.all
  @comment = Comment.new
  @comments = Comment.where(notion: @notion)


end



  # GET /notions/new
  def new
    @notion = Notion.new
  end


  # GET /notions/1/edit

  def edit
  end

  # POST /notions
  # POST /notions.json
  def create
    @notion = Notion.new(notion_params)

    respond_to do |format|
      if @notion.save
        format.html { redirect_to @notion, notice: 'Notion was successfully created.' }
        format.json { render :show, status: :created, location: @notion }
      else
        format.html { render :new }
        format.json { render json: @notion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notions/1
  # PATCH/PUT /notions/1.json
  def update
    respond_to do |format|
      if @notion.update(notion_params)
        format.html { redirect_to @notion, notice: 'Notion was successfully updated.' }
        format.json { render :show, status: :ok, location: @notion }
      else
        format.html { render :edit }
        format.json { render json: @notion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notions/1
  # DELETE /notions/1.json
  def destroy
    @articles = Article.where("notion_id")
    @notion.destroy
    respond_to do |format|
      format.html { redirect_to notions_url, notice: 'Notion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notion
      @notion = Notion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notion_params
      params.require(:notion).permit(:name, :photo)
    end
    # Never trust parameters from the scary internet, only allow the white list through.

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def choice
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/notions_helper.rb
module NotionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <%= f.label :titre %>
    <%= f.text_field :titre %>
    <%= f.label :year, 'date sur timeline' %>
    <%= f.number_field :year %>
    <%= f.text_area :content %>
    <%= f.file_field :photo %>
    <%= f.file_field :audio %>
    <%= f.file_field :video %>
    <% notions_array = Notion.all.map { |notion| [notion.name, notion.id] } %>
    <%= f.select :notion_ids, options_for_select(notions_array), {}, {:multiple => true} %>
    <%= f.submit :submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="fluid-container">
    <div class="row">
      <div class="col-md-12">
        <div class="text-center"><%= link_to 'En savoir plus',  pages_ensavoirplus_path%></div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <h1 class="text-center"><%= link_to 'Twice', pages_home_path %></h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notions/_form.html.erb
<%= form_for(@notion) do |f| %>
<% if @notion.errors.any? %>
<% @notion.errors.full_messages.each do |message| %>
<div><%= message %></div>
<%end%>
<%end%>

  <%= f.text_field :name %>
  <%= f.file_field :photo %>
    <%= f.submit :submit %>

  </div>
<% end %>

app/views/notions/edit.html.erb
<h1>Editing Notion</h1>

<%= render 'form', notion: @notion %>

<%= link_to 'Show', @notion %> |
<%= link_to 'Back', notions_path %>

app/views/notions/index.html.erb
<%= render 'layouts/header'%>
<p id="notice"><%= notice %></p>


 <h2 class="text-center"> Comprendre le numérique à travers 100 notions... </h2>
 <div class="text-center">
 <input class="text-center" type="search" placeholder="Entrez un mot-clef" name="the_search">
 </div>
<div class="container notion col-md-8 col-md-offset-2 notions">
    <div class="row">
    <% @notions.each do |notion| %>
        <td><%= link_to (image_tag notion.photo, width: 300), notion%></td>
    <% end %>
    </div>
</div>

app/views/notions/new.html.erb
<h1>New Notion</h1>

<%= render 'form', notion: @notion %>

<%= link_to 'Back', notions_path %>

app/views/notions/show.html.erb
<%= render 'layouts/header'%>
<p id="notice"><%= notice %></p>

<p class="text-center">
  Comprenez l'évolution du numérique à travers le thème de
  <%= @notion.name %>
  grâce à ces articles :
</p>
<div class="container notion col-md-8 col-md-offset-2 notions">
    <div class="row">
    <% @notion.articles.each do |article| %>
        <td><%= link_to article.titre, article_path%></td>
        <% end %>
    </div>
</div>



<div class="container notion col-md-8 col-md-offset-2 notions">
    <div class="row">
    <% @comments.each do |comment| %>
        <td><%= comment.name%></td>
        <td><%= comment.birthday%></td>
        <td><%= comment.content%></td>
        <% end %>
    </div>
</div>

<div class="container notion col-md-8 col-md-offset-2 notions">
  <div class="row">

    <%= form_for :comment, url: create_comment_path(@notion) do |f| %>

    <%= f.label :name, 'Votre nom' %>
    <%= f.text_field :name %>
    <%= f.label :birthday, 'Naissance' %>
    <%= f.date_field :birthday %>
    <%= f.label :content, 'Votre histoire' %>
    <%= f.text_field :content %>
    <%= f.submit :submit %>
    <% end %>
  </div>
</div>




<%= link_to 'Back', notions_path %>

app/views/pages/choice.html.erb
<%= render 'layouts/header'%>



  <div class="container choice">
      <div class="row">
          <div class="text-center">
              <p id="suivreHistoire">COMPRENDRE L'HISTOIRE DU NUMERIQUE</p>
          </div>
          <div class="images">
          <div class="image_gauche">
            <%=link_to (image_tag("suivrehistoire.jpg", alt: "suivre l'histoire")) %>
          </div>
          <div class="image_droite">
            <%=link_to (image_tag("choisirnotion.jpg", alt: "choisir une notion")), notions_path %>
          </div>
      </div>
    </div>
  </div>
<%= render 'layouts/footer'%>







<script>
$(document).ready(function() {
$("body").css("display", "none");

$("body").fadeIn(2000);

$("a.transition").click(function(event){
    event.preventDefault();
    linkLocation = this.href;
    $("body").fadeOut(1000, redirectPage);
});

function redirectPage() {
    window.location = linkLocation;
}
});
</script>

app/views/pages/ensavoirplus.html.erb
<%= render 'layouts/header'%>
<div class="fluid-container">
  <div class="row">
    <div class="col-md-3 col-md-offset-3">
    <h2 class="text-center">Notre projet</h2>
  </div>

    <div class="col-md-6 col-md-offset-3">
      <p>
Le diplôme de MMI ( Métiers du Multimédia et de l'Internet ) ouvre ses étudiants à l’un des volets les plus décisifs de notre temps, des plus contradictoires aussi : ​le numérique.​ Tant du côté de la réflexion que celui de la maîtrise de ses objets, cette formation est exigeante. Elle nécessite que les étudiants puissent en acquérir les fondements technologiques, dépassant le statut d’usager. Elle requiert également qu’ils en comprennent les enjeux sociétaux, intellectuels, juridiques, financiers... dépassant la position de consommateur.
</p><p>C’est donc autour de cette vaste mais primordiale notion que s’atteleront Benjamin MOQUET, Florian VILLAGER, Fleur GRIFFON, Yann LE ROUX, Elisa MAUGER, Swann LATASA, Thomas HAWKINS, Gala HERIL, David LAURES, Gwendal VALENTINE, Ines LE BUHAN, Margaux JESTIN, Elie MARGOET, Noemi LAMANE, Aurelien LAFON et Emma JOUFFROY.
 </p><hr>

                        <p>Les projets Tuteurés font parti d’un module obligatoire prévu dans le PPN en DUT MMI. Cette année, les projets Tuteurés sont encadrés par Mr Cattelain et Mme Bornerie, et s’étendront sur une période de 18 mois.
Nous avons pour objectif de « présenter notre aventure numérique » à travers un outil multimédia jusqu’à un forum, le « for in » durant lequel nous présenterons nos projets.
C’est après de nombreux brainstormings avec tout l’équipe du projet que nous sommes arrivés à l’idée de créer « Twice ».
Twice est un site web immersif, qui pousse l'interactivité du visiteur à son maximum. Dans un Design simple et épuré, mêlant photographies, vidéos, motion design, sons, articles, ..., notre site web permettra à l’utilisateur de naviguer entre la vie de deux jumeaux qui racontent leurs visions du numériques.
Aujourd’hui, nous sommes encore au stade de prototype. Après nous être mis d’accord sur un ensemble de points qui nous semblaient essentiels, comme l’idée même du site immersif, mais aussi la manière de naviguer sur ce site pour l’utilisateur ou encore le design même du site, nous nous sommes répartis des rôles entre premières et deuxièmes années.
Nous avons pour ambition lors de la présentation finale de notre site, mais d’autant plus lors du forum qui se déroulera en 2018, de faire voyager nos auditeurs dans la vie de nos deux personnages, mais aussi à travers différentes cultures, et qu’il y découvrent notre vision du numérique. </p>


  </div>
</div>

<%= render 'layouts/footer'%>

app/views/pages/home.html.erb
  <div class="container-fluid home">

    <div class="row logo">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center"><%=link_to (image_tag("main_logo.png", alt: "main_logo", id:"big_logo")), pages_choice_path%></h1>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6 text-center col-md-offset-3 drapeaux">
          <%=link_to (image_tag("left-arrow-head.png", alt: "Example Image"))%>
          <%=image_tag("spain.png", alt: "Example Image", id:"spain")%>
          <%=link_to (image_tag("france.png", alt: "Example Image", id:"france")), pages_choice_path%>
          <%=image_tag("united-kingdom.png", alt: "Example Image", id:"uk")%>
          <%=link_to (image_tag("right-arrow-head.png", alt: "Example Image"))%>
      </div>
    </div>
  </div>
  <%= render 'layouts/footer'%>